# this is the data I need to construct a team workspace for the 2029/cgg initiative
# read the data file
# create each entry as a page
# add a question or team_info as shown
# add the items as appropriate


team_page:
  page_title:   Proposal home page
  chat_title:   General team chat
  nav_title:    Proposal home page
  team_info:    yes
  order: 1


framework:
  page_title:   What is the change you want to make?
  chat_title:   Chat about the framework
  nav_title:    Framework
  question:         What are the key elements of a framework for analyzing online options?
  idea_criteria:    5..1000
  answer_criteria:  5..1500
  num_answers:      1000
  order: 2

technologies:
  page_title:   Who would this change affect and how?
  chat_title:   Chat about technologies 
  nav_title:    Technologies
  question:         What are the most important technologies to introduce and explore?
  idea_criteria:    5..1000
  answer_criteria:  5..1500
  num_answers:      1000
  order: 3

case_studies:
  page_title:   Why would this change be important for your community? 
  chat_title:   Chat about case studies
  nav_title:    Case studies
  question:         What are the best case studies?
  idea_criteria:    5..1000
  answer_criteria:  5..1500
  num_answers:      1000
  order: 4

next_steps:
  page_title:   What are some options for implementing this change?
  chat_title:   Chat about next steps
  nav_title:    Next steps
  question:         'DIY Next steps: How can we help people integrate online tools into their own practice?'
  idea_criteria:    5..1000
  answer_criteria:  5..1500
  num_answers:      1000
  order: 5


recommendation_page:
  page_title:   What do you recommend?
  chat_title:   Chat about the outline
  nav_title:    Outline
  question:         Bringing it altogether - What is the outline for the presentation?
  idea_criteria:    5..1000
  answer_criteria:  5..1500
  num_answers:      1000
  order: 6
