# Format notes
# haml string formatting is critical
#   Always follow these two examples
#      haml: |
#        %p We need to hear from you!
#
#      haml: |
#        %p 
#          We need to hear from you. Please #{link_to 'rate', question_worksheet_path(question), {:class=> 'display_worksheet', :remote => true}}
#          these talking points and #{link_to 'tell us', question_worksheet_path(question), {:class=> 'display_worksheet', :remote => true}} what you think
#
#   Always use a pipe '|' after haml:
#   Always indent multiline haml nodes
#

init_1: 
  
  question_top:
    option_1:
      test: 'true'
      haml_strings:
        primary:
          haml: |
            %p #{@member.first_name}, V2 these talking points were hand selected and ordered to reflect the preferences of the group |
            %p= link_to "Learn more about this hand selected list", help_curate_show_path, {:remote=>true}
        secondary: 
          haml: |
            %p We need to hear from you!

  question_summary_above_curated_list:
    option_member_new:
      test: (!@member.nil? && @member.id != 0 && data[:question].show_new)
      haml_strings:
        primary:
          haml: |
            %p #{@member.first_name}, please
            %ul
              - if question.unrated_talking_points > 0
                %li 
                  = link_to 'Rate', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.unrated_talking_points, ' new talking point')
              - if question.updated_talking_points > 0
                %li 
                  = link_to 'Review', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.updated_talking_points, ' updated talking point')
              - if question.new_coms > 0
                %li 
                  = link_to 'Read', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.new_coms, ' new comment')

    option_member_no_new:
      test: (!@member.nil? && @member.id != 0 && !data[:question].show_new)
      haml_strings:
        primary:
          haml: |
            %p #{@member.first_name}, please
            %ul
              - if question.num_talking_points > 0
                %li 
                  = link_to 'Review', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.num_talking_points, ' talking point') 
                  and compare to this list of answers
                %li 
                  = link_to 'Add', question_worksheet_path(question), {:class => 'cta'}
                  a talking point for this question
                
              - elsif question.num_talking_points == 0
                %li 
                  = link_to 'Add', question_worksheet_path(question), {:class => 'cta'}
                  a talking point for this question
                  
    option_visitor:
      test: (@member.nil? || @member.id == 0)
      #data[:question].num_talking_points.to_i>0 && data[:question].coms.to_i>0
      haml_strings:
        primary:
          haml: |
            %p
              We'd like to hear from you
            %ul
              %li Help us create a set of talking points to answer this question.
              - if question.num_talking_points > 0
                %li 
                  = link_to 'Review', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.unrated_talking_points, ' talking point') 
              - if question.coms > 0
                %li 
                  = link_to 'Browse', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.coms, ' comment') 

  question_summary_above_default_list:
    option_member_new:
      test: (!@member.nil? && @member.id != 0 && data[:question].show_new)
      haml_strings:
        primary:
          haml: |
            %p #{@member.first_name}, please
            %ul
              - if question.unrated_talking_points > 0
                %li 
                  = link_to 'Rate', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.unrated_talking_points, ' new talking point')
              - if question.updated_talking_points > 0
                %li 
                  = link_to 'Review', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.updated_talking_points, ' updated talking point')
              - if question.new_coms > 0
                %li 
                  = link_to 'Read', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.new_coms, ' new comment')

    option_member_no_new:
      test: (!@member.nil? && @member.id != 0 && !data[:question].show_new)
      haml_strings:
        primary:
          haml: |
            %p #{@member.first_name}, please
            %ul
              - if question.num_talking_points > 0
                %li 
                  = link_to 'Review', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.num_talking_points, ' talking point') 
                %li 
                  = link_to 'Add', question_worksheet_path(question), {:class => 'cta'}
                  a talking point for this question
                
              - elsif question.num_talking_points == 0
                %li 
                  = link_to 'Add', question_worksheet_path(question), {:class => 'cta'}
                  a talking point for this question
                  
    option_visitor:
      test: (@member.nil? || @member.id == 0)
      #data[:question].num_talking_points.to_i>0 && data[:question].coms.to_i>0
      haml_strings:
        primary:
          haml: |
            %p
              We'd like to hear from you
            %ul
              %li Help us create a set of talking points to answer this question.
              - if question.num_talking_points > 0
                %li 
                  = link_to 'Review', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.unrated_talking_points, ' talking point') 
              - if question.coms > 0
                %li 
                  = link_to 'Browse', question_worksheet_path(question), {:class => 'cta'}
                  = pluralize(question.coms, ' comment') 
    
              
              
              
              
              
  
  question_summary_below_curated_list:
    option_1:
      test: data[:question].num_talking_points.to_i>0 && data[:question].coms.to_i>0
      haml_strings:
        primary:
          haml: |
            %p 
              #{link_to (@member.nil? || @member.id == 0 ? 'Explore' : 'Review'), question_worksheet_path(question), {:remote=> true}} 
              #{question.num_talking_points.to_i>0 ? pluralize(question.num_talking_points, 'talking point') : ''} 
              #{question.num_talking_points.to_i>0 && question.coms.to_i>0 ? 'and ' : ''}
              #{question.coms.to_i>0 ? pluralize(question.coms, 'comment') : ''}
            %p 
              We need to hear from you. Please #{link_to 'rate', question_worksheet_path(question), {:class=> 'display_worksheet', :remote => true}}
              these talking points and #{link_to 'tell us', question_worksheet_path(question), {:class=> 'display_worksheet', :remote => true}} what you think
      

  question_summary_below_default_list:
    option_1:
      test: 'true'
      haml_strings:
        primary_1:
          test: data[:question].coms.to_i > 0 && (@member.nil? || @member.id == 0)
          haml: |
            %p #{link_to 'Explore', question_worksheet_path(question), {:remote=> true}} #{pluralize(question.coms, 'comment')}
        primary_2:
          test: data[:question].coms.to_i > 0 && (!@member.nil? && @member.id != 0)
          haml: |
            %p #{link_to 'Review', question_worksheet_path(question), {:remote=> true}} #{pluralize(question.coms, 'new comment')}
        primary_3: 
          haml: |
            %p 
              Click to #{link_to 'suggest a talking point', question_worksheet_path(question), {:remote=> true}} 
              or #{link_to 'discuss this question', question_worksheet_path(question), {:remote=> true}}

  endorsement:
    option_1:
      test: data[:endorsed] == false
      haml_strings:
        primary:
          haml: |
            %p 
              If you agree with this proposal, show your support by endorsing it. Add a statement of support in the form below and click the button.
              If you disagree, join the discussion to share your concerns and suggest improvements. 
              #{link_to "Here's how", help_path(:topic=>'Help_develop_proposal'), {:remote=>true}}

  end_summary_print:
    option_1:
      haml_strings:
        primary:
          haml: |
            %p= link_to "Print this proposal", print_proposal_path(@team)			

  summary_page_submit:
    option_1:
      haml_strings:
        primary:
          haml: |
            %p #{link_to 'Request pre-submission review', submit_proposal_path(@team.id, :act => 'pre_review'), {:class=>"pre_review_proposal", :rel=>'nofollow', :remote=>true}} (Recommended)
            %p= link_to "Submit this proposal to the #{sponsor}", submit_proposal_path(@team.id, :act => 'submit'), {:class=>"submit_proposal", :rel=>'nofollow', :remote=>true}

  curated_talking_points_list:
    option_1:
      test: data[:custom_class] == 'curated'
      haml_strings:
        primary:
          haml: |
            %p These talking points were hand selected and ordered to reflect the preferences of the group
            %p= link_to "Learn more about this hand selected list", help_curate_show_path, {:remote=>true}
    option_2:
      test: data[:custom_class] == 'non_curated'
      haml_strings:
        primary:
          haml: |
            %p These are the top talking points from the group
            %p= link_to "Learn about hand selecting this list", help_curate_show_path, {:remote=>true}
    option_3:
      test: data[:custom_class] == 'curator'
      haml_strings:
        primary:
          haml: |
            %h4 You can help create this list
            %ul
              %li Select talking points from the left by dragging them into the list above
              %li Arrange the list items by dragging them up or down
              %li This list should reflect the ratings and favorites of the group
            %p= link_to "Show me how to edit this list", help_curate_show_path, {:remote=>true}

  worksheet_top:
    option_1:
      test: 'true'
      haml_strings:
        primary:
          haml: |
            %p Please create, discuss, rate and refine the talking points below to answer this question and find those that are acceptable to most of our community
        secondary:
          haml: |
            %p= link_to image_tag('close_icon_16.gif',{:title=>'Click to close worksheet', :class=>'close_worksheet'}) + "Close this talking points worksheet", question_summary_path(question.id), :remote=>true, :class=>'close_worksheet'

  worksheet_cta:
    option_1:
      test: 'true'
      haml_strings:
        primary_1:
          test: '@add_tp == true'
          haml: |
            %p If you have a specific idea for answering this question, please add a talking point in the form below, Or you can share your thoughts in a comment
        primary_2:
          test: '@rate_tp == true'
          haml: |
            %p Click the circle below the colored bar to indicate how you feel about each talking point. Your choices range from perfectly acceptable (dark green) to completely unacceptable (dark red)
        primary_3:
          test: '@fav_tp == true'
          haml: |
            %p Click the star to mark the talking points your prefer. If you click more than 5 talking points for one question, you will be prompted to choose your 5 most favorite.
        primary_4:
          test: '@com_tp == true'
          haml: |
            %p You can comment on the talking points by clicking the Reply/Comments under each talking point

