# this is the data I need to seed participation_event_descriptions
# read the data file
# add each question as shown

item1: 
  id: 1
  col_name: 'comments'
  code: 'com'
  description: 'Add comment'
  summary_order: 40
  summary_title: 'comment'
  points: 120
  min_length: 40 

item2: 
  id: 2
  col_name: ''
  code: 'e_com'
  description: 'Edit comment'
  points: 0
    
item3:
  id: 3
  col_name: 'talking_points'
  code: 'tp'
  description: 'Add talking point'
  #summary_order: 8
  summary_title: 'talking point'
  points: 200
    
item4:
  id: 4
  col_name: 'talking_point_edits'
  code: 'e_tp'
  description: 'Edit talking point'
  #summary_order: 9
  summary_title: 'talking point edit'
  points: 80
    
item5:
  id: 5
  col_name: ''
  code: 'ans'
  description: 'Add answer'
  #summary_order: 0
  summary_title: 'answer'
  points: 600
    
item6:
  id: 6
  col_name: ''
  code: 'e_ans'
  description: 'Edit answer'
  #summary_order: 0
  summary_title: 'answer edit'
  points: 240
    
item7:
  id: 7
  col_name: 'endorsements'
  code: 'end'
  description: 'Add endorsement'
  #summary_order: 20
  summary_title: 'endorsement'
  points: 120
    
item8:
  id: 8
  col_name: ''
  code: 'e_end'
  description: 'Update endorsement'
  points: 0
    
item9:
  id: 9
  col_name: ''
  code: 'proposal'
  description: 'Add proposal idea'
  points: 800

item10:
  id: 10
  col_name: ''
  code: 'proposal'
  description: 'Update proposal idea'
  points: 0
    
item11:
  id: 11
  col_name: 'friend_invites'
  code: 'invite'
  description: 'Invite friend'
  summary_order: 15
  summary_title: 'friend invite'
  points: 50
    
item13:
  id: 13
  col_name: 'content_reports'
  code: 'report'
  description: 'Report content'
  #summary_order: 12
  summary_title: 'content report'
  points: 40
    
item15:
  id: 15
  col_name: ''
  code: 'init'
  description: 'Join initiative'
  points: 96
    
item17:
  id: 17
  col_name: 'talking_point_ratings'
  code: 'rate_tp'
  description: 'Rate talking point'
  #summary_order: 10
  summary_title: 'talking point rating'
  points: 40
    
item19:
  id: 19
  col_name: 'talking_point_preferences'
  code: 'prefer_tp'
  description: 'Prefer talking point'
  #summary_order: 11
  summary_title: 'preferred talking point'
  points: 80
    
item21:
  id: 21
  col_name: ''
  code: 'rate_ans'
  description: 'Rate answer'
  #summary_order: 25
  summary_title: 'answer rating'
  points: 60

item22: 
  id: 22
  col_name: 'ideas'
  code: 'idea'
  description: 'Add idea'
  summary_order: 30
  summary_title: 'idea'
  points: 200
  min_length: 10 

item23: 
  id: 23
  col_name: ''
  code: 'e_idea'
  description: 'Edit idea'
  points: 0

item24:
  id: 24
  col_name: 'idea_ratings'
  code: 'rate_idea'
  description: 'Rate idea'
  summary_order: 35
  summary_title: 'idea rating'
  points: 40

item26: 
  id: 26
  col_name: 'themes'
  code: ''
  description: 'Add theme'
  summary_order: 25
  summary_title: 'answer'
  points: 200
  min_length: 10 

item27: 
  id: 27
  col_name: ''
  code: 'e_theme'
  description: 'Edit theme'
  points: 0

item28:
  id: 28
  col_name: 'theme_ratings'
  code: 'rate_theme'
  description: 'Rate theme'
  summary_order: 28
  summary_title: 'answer rating'
  points: 40

item100:
  id: 100
  col_name: 'proposal_views'
  code: 'summary'
  description: 'Load proposal summary'
  #summary_order: 4
  summary_title: 'proposal view'
  points: 20
    
item101:
  id: 101
  col_name: 'question_views'
  code: 'worksheet'
  description: 'Load question worksheet'
  #summary_order: 5
  summary_title: 'question view'
  points: 20
    
item102:
  id: 102
  col_name: ''
  code: 'new'
  description: 'Load new content'
  points: 20
    
item103:
  id: 103
  col_name: ''
  code: '_mlc'
  description: 'Visit with _mlc code'
  points: 30
    
item104:
  id: 104
  col_name: ''
  code: 'profile_pic'
  description: 'Upload profile picture'
  points: 120
    
item105:
  id: 105
  col_name: ''
  code: 'help'
  description: 'Request help'
  points: 40
          
item106:
  id: 106
  col_name: ''
  code: 'new_profile'
  description: 'Create a new profile'
  points: 96
    
item107:
  id: 107
  col_name: 'followers'
  code: 'notification'
  description: 'Update notification settings'
  summary_order: 10
  summary_title: 'follower'
  points: 160

item1000:
  id: 1000
  col_name: 'points_total'
  code: 'total_points'
  description: 'Total team points'
  summary_order: 100
  summary_title: 'total team points'
  points: 0
