# this is the data I need to construct a proposal plan for the 2029/cgg initiative
# read the data file
# add each question as shown

what_page:
  question:         What does this vision look like in detail?
  order_id: 1
  default_answer_id: 10
  num_answers:      1
  answer_criteria:  5..4000
  talking_point_criteria: 20..200
  talking_point_preferences:  5

why_page:
  question:         How might this project build civic infrastructure or help bridge divides?
  order_id: 2
  default_answer_id: 11
  num_answers:      1
  answer_criteria:  5..4000
  talking_point_criteria: 20..200  
  talking_point_preferences:  5

how_page:
  question:         What people and skills are valuable to this project?
  order_id: 3
  default_answer_id: 12
  num_answers:      1
  answer_criteria:  5..4000
  talking_point_criteria: 20..200
  talking_point_preferences:  5

who_page:
  question:         How are we going to make this project happen?
  order_id: 4
  default_answer_id: 13
  num_answers:      1
  answer_criteria:  5..4000
  talking_point_criteria: 20..200
  talking_point_preferences:  5

