chdir: /ce_development/Rails/tp
environment: development
address: 0.0.0.0
port: 8001
timeout: 30
#log: log/thin.log
pid: log/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 30
servers: 1
daemonize: true